# Generated by Django 4.2.11 on 2025-04-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
