# Generated by Django 4.2.11 on 2025-04-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_alter_commit_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
