name: Netflix API CI

on: [push]

jobs:
  run-tests:
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: music.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install Requirements
        run: pip install --break-system-packages --use-deprecated=legacy-resolver -r requirements.txt

      - name: Run Tests
        run: pytest
      - name: Show installed packages
        run: pip list
