name: Netflix API CI
on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: music.settings
      steps:
        - uses: action/checkout@v2
        - uses: action/setup-python@v2
          with:
            python-version: 3.12
        - name: Install Requirements
          run: pip install -r requirements.txt
        - name: Run Tests
          run: pytest